[송은] Zzim 컴포넌트
Together-3team/petFrontend pull request #101
Opened 2024-06-05 00:46 UTC by q45402sk

## 🔥관련 이슈

- #80 

## :grin:주요 변경 사항

- zzim 컴포넌트 
- card 컴포넌트 수정

## 📄스크린샷
![pet-zzim](https://github.com/Together-3team/petFrontend/assets/56138199/d2e7177c-9b43-4fd5-9d7c-b3b316d484c7)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- accessToken 갱신이 안 돼서 테스트는 못 해봤습니다.
- 사용예시는 test/card  폴더에 있습니다.

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-05 01:51 UTC, devwqc requested changes
송은님 감사합니다!! 👍👍👍👍👍🥇🥇🥇🥇

고민 많이 하신 티가 나네요!👍
다만 미리 초안 작업을 하셔서 API 연동하면 변경할 부분이 꽤 생길 거 같아요

지금은 페이지 우측 하단에 찜 버튼이 생기는 이슈만 해결해 주시면 될 거 같습니다👍

2024-06-05 01:51 UTC, devwqc commented on src/components/common/Card/index.tsx
> +  zzim?: boolean;
💊 `boolean` 값이니까 `isZzim` 처럼 `boolean` 값을 유추할 수 있는 네이밍이 더 좋을 거 같아요~

2024-06-05 01:51 UTC, devwqc commented on src/components/common/Zzim/index.tsx
> +      queryClient.setQueryData(['likeStatus', productId], () => userAction === 'LIKE_PRODUCT');
💊 다음에 회의에서 얘기 나눠서 쿼리 키랑 userAction은 따로 상수로 관리해보죠!

2024-06-05 01:51 UTC, devwqc commented on src/pages/test/card/index.tsx
> +      <Zzim className={styles.zzim} color="gray" productId={2} />
❓지금 /test/card 접속해서 오른쪽 하단에 보면 찜이 보이던데 이건 뭘까요??
![스크린샷 2024-06-05 104010](https://github.com/Together-3team/petFrontend/assets/98067115/961b6d2b-7554-4c14-94e5-ca165944191c)

2024-06-05 01:51 UTC, devwqc commented on src/components/common/Card/Card.module.scss
> +    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
💊아마 모바일에서 누를 때 검은색 테두리 같은 거 생겨서 적용하신 거 같은데 만약 그렇다면 `rgba(0, 0, 0, 0)`보다 `transparent`로 하면 어떨까요?

2024-06-05 01:51 UTC, devwqc commented on src/components/common/Zzim/index.tsx
> +  const { data: isProductLikedByCurrentUser } = useQuery({
❓여기서 `true` 값이 넘어오면 찜 눌렀을 때 해제 될까요?

2024-06-05 03:21 UTC, Seoin02 approved these changes
👍🏻낙관적 업데이트도 적용하시고 정말 고생많으셨습니다!!! 최고

2024-06-05 03:21 UTC, Seoin02 commented on src/components/common/Card/index.tsx
>    //title이 큰 카드, 작은 카드 각각의 너비를 초과하면 글씨가 흐르도록 함
👍🏻흐르는 상품명읻 사용성을 높여줄 것 같습니다! 굿

2024-06-05 03:21 UTC, Seoin02 commented on src/components/common/Zzim/index.tsx
> +  const likesMutation = useMutation({
👍🏻낙관적 업데이트 적용하느라 고생많으셨습니다ㅠㅠ

2024-06-05 03:21 UTC, Seoin02 commented on src/utils/zzim.ts
> +    headers: {
💬얼른 작업하겠습니다

2024-06-05 03:23 UTC, minyoung0503 approved these changes
고생하셨어요 송은님 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🤍

2024-06-07 02:09 UTC, q45402sk commented on src/pages/test/card/index.tsx
> +      <Zzim className={styles.zzim} color="gray" productId={2} />
상품 상세에서 사용하려고 예시로 추가해뒀습니다!

2024-06-08 11:02 UTC, q45402sk commented on src/components/common/Zzim/index.tsx
> +  const { data: isProductLikedByCurrentUser } = useQuery({
네 74번째 줄에 있어요!

2024-06-08 11:03 UTC, q45402sk commented on src/components/common/Card/Card.module.scss
> +    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
반영했습니다!

2024-06-08 11:04 UTC, devwqc approved these changes

2024-06-08 11:09 UTC, merged