[지원] Payment UI 구현
Together-3team/petFrontend pull request #105
Opened 2024-06-05 03:58 UTC by seolsis

## 🔥관련 이슈

- 결제 페이지 UI 구현

## :grin:주요 변경 사항

- 체크박스
- 버튼 비활성화 기능

## 📄스크린샷
![payment](https://github.com/Together-3team/petFrontend/assets/88234067/b89b5a3d-eaea-4d03-848f-9796547c2d23)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-05 04:49 UTC, Seoin02 requested changes
👍🏻지원님 고생 많으셨습니다!!

2024-06-05 04:49 UTC, Seoin02 commented on src/components/payment/Card.tsx
> +    <>
❗️불필요한 프래그먼트 태그 제거해도 좋을 듯 합니다

2024-06-05 04:49 UTC, Seoin02 commented on src/components/payment/PaymentAgree.module.scss
> +.check:checked::before {
👍🏻오 체크박스 이렇게 구현하셨군요?!

2024-06-05 04:49 UTC, Seoin02 commented on src/components/payment/PaymentAgree.tsx
> +    <>
❗️불필요한 프래그먼트 태그 제거하면 좋을 듯 합니다.

2024-06-05 04:49 UTC, Seoin02 commented on src/pages/Payment/fail.tsx
> +  return <div>결제실패ㅜ</div>;
💬ㅜ는 의도하신거죠?

2024-06-05 04:49 UTC, Seoin02 commented on src/pages/Payment/index.tsx
> +import Button from '@/components/common/Button';
❗️import order 컨벤션 고려하면 좋을 것 같습니다

2024-06-05 04:49 UTC, Seoin02 commented on src/pages/Payment/index.tsx
> +          <div className={styles.line}></div>
❓JSX로 안 쓴 이유가 있을까요?

2024-06-05 04:49 UTC, Seoin02 commented on src/pages/Payment/index.tsx
> +    TossPayments: any;
❓어느 응답값이 들어올 지 몰라서 any로 선언 하신건가요?

2024-06-05 05:30 UTC, devwqc requested changes
지원님 감사합니다! 👍💯👍💯👍💯

결제 경로가 `pages/Payment`로 되어 있는데 소문자로 맞추면 좋을 거 같아요~

2024-06-05 05:30 UTC, devwqc commented on package.json
> +    "dotenv": "^16.4.5",
❓💊 next에서 환경변수 알아서 인식해서 `dotenv` 패키지 설치하지 않아도 동작하지 않나요??
만약 동작하면 제거해도 될 거 같아요~

2024-06-05 05:30 UTC, devwqc commented on .gitignore
> +.env.local
❓💊 `.gitignore` 30번 라인에 `.env*.local` 있어서 필요 없을 거 같다고 생각 드는데 혹시 추가하신 `.env.local` 삭제했을 때 깃에 올라가나요?

2024-06-05 08:03 UTC, minyoung0503 approved these changes
지원님 고생하셨어오 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2024-06-06 11:54 UTC, seolsis commented on src/pages/Payment/index.tsx
> +          <div className={styles.line}></div>
엇 이유는 따로 없습니다..!

2024-06-06 11:54 UTC, seolsis commented on src/pages/Payment/index.tsx
> +    TossPayments: any;
넵 추후 수정하겟습니다

2024-06-06 11:55 UTC, seolsis commented on src/pages/Payment/fail.tsx
> +  return <div>결제실패ㅜ</div>;
오타같습니다..

2024-06-07 00:50 UTC, Seoin02 commented on src/pages/Payment/index.tsx
> +          <div className={styles.line}></div>
빈태그를 사용하면 웹접근성이 낮아질 수 있다고 알고 있어서 내용이 없으면 JSX로 수정하는게 좋을 것 같아요!

2024-06-08 12:06 UTC, seolsis commented on src/pages/Payment/index.tsx
> +          <div className={styles.line}></div>
넵 다른 페이지도 저렇게 했어서 전부 수정하겠습니다!

2024-06-08 13:20 UTC, Seoin02 approved these changes

2024-06-10 09:59 UTC, devwqc approved these changes

2024-06-11 09:58 UTC, seolsis commented on .gitignore
> +.env.local
밑에 있는 줄 모르고 추가해서 삭제했습니다!

2024-06-11 10:01 UTC, merged