[서인] my로그인o 페이지 / UI 구현
Together-3team/petFrontend pull request #114
Opened 2024-06-07 12:22 UTC by Seoin02

## 🔥관련 이슈

- #84 

## :grin:주요 변경 사항

- NextButton 공통 컴포넌트 구현

## 📄스크린샷
<img width="386" alt="스크린샷 2024-06-07 오후 9 18 04" src="https://github.com/Together-3team/petFrontend/assets/144193370/be34964b-7866-42d1-a0b8-c5ec077adf47">

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- API 연결 후 닉네임과 프로필 이미지에 데이터 넣겠습니다.
- 인증 후 my>index.txs 파일에 합치겠습니다.
- 나머지 페이지 구현 후 NextButton에 href 넣겠습니다.
 
## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-07 13:19 UTC, devwqc requested changes
서인님 감사합니다👍💯👍💯👍💯👍💯

서인님이 전체적으로 페이지가 많으신데 뚝딱 잘 나오는 거 같아요👍
인증 관련해서는 저도 같이 고민해 볼게요 같이 후딱 해치우죠!

2024-06-07 13:19 UTC, devwqc commented on src/components/common/Button/NextButton/index.tsx
> +      </button>
💊 해당 컴포넌트는 `Link`의 기능을 하고 있으니까 안에 `button`을 넣을 필요는 없을 거 같아요~
그리고 보편적으로 `Link`, `button`은 닫는 태그를 사용하니까 `text`보다 `children`을 받으면 조금 더 `NextButton`의 이름에 맞는 사용법이 되지 않을까 싶습니다!

추가적으로 `Link`에는 속성이 어마어마하게 많아서 `href`만 받는 것보다 `LinkProps`로 `rest`를 넘겨주면 어떨까 싶은데 서인님 생각은 어떠실까요?

2024-06-07 13:19 UTC, devwqc commented on src/components/common/Button/BackButton/index.tsx
👍 `BackButton`이 `Button` 폴더 밖에 있는 것이 조금 신경 쓰였는데 좋네요 좋네요

2024-06-07 13:19 UTC, devwqc commented on src/constants/index.ts
> +export const API_BASE_URL = 'http://localhost:3000';
💊 저희 `API_BASE_URL` 상수로 관리하지 말고 `env`로 관리할까요? 이렇게 되니까 계속 소스를 수정하는 번거로움이 있는 거 같아요!

2024-06-07 13:19 UTC, devwqc commented on src/pages/my/menu.tsx
> +      <NavBottom />
👍따로 사용법 안 알려드려도 뚝딱 잘 적용하셨네요

2024-06-07 13:19 UTC, devwqc commented on src/pages/my/menu.tsx
> +        <NextButton text="내 리뷰" href="" />
👍반복되는 요소들 컴포넌트로 분리한 거 너무 좋아요~

2024-06-07 13:19 UTC, devwqc commented on src/pages/signup/index.tsx
>        </div>
💊여기 가능하면 `Header` 컴포넌트 적용 한번 해주시면 감사하겠습니다

2024-06-07 14:32 UTC, Seoin02 commented on src/components/common/Button/NextButton/index.tsx
> +      </button>
반영했습니다

2024-06-07 14:39 UTC, Seoin02 commented on src/pages/signup/index.tsx
>        </div>
적용했습니다

2024-06-10 06:20 UTC, devwqc approved these changes

2024-06-10 07:47 UTC, minyoung0503 approved these changes
고생하셨어요 서인님 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️

2024-06-10 08:47 UTC, merged