[민영] 별점 컴포넌트 구현
Together-3team/petFrontend pull request #12
Opened 2024-05-22 05:58 UTC by minyoung0503

## 🔥관련 이슈

- #5 

## :grin:주요 변경 사항

- 별점 컴포넌트 구현

## 📄스크린샷
### `editable = true`

https://github.com/Together-3team/petFrontend/assets/155047307/db8e88a6-6728-4282-b465-888bda381c94

### `editable = false`
<img width="89" alt="스크린샷 2024-05-22 오후 2 20 29" src="https://github.com/Together-3team/petFrontend/assets/155047307/c5b733cb-e5db-4741-ae22-63b21cef317f">

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)
‼️ react icon 라이브러리를 사용한 별점 컴포넌트가 있어서 사용해봤어요 ! ‼️
‼️ rating prop은 필수입니다 ! ‼️

### `editable = true` (리뷰 작성)
* 사용 예시
```typescript
const [stars, setStars] = useState(0);

<StarRating rating={stars} onRate={setStars} editable />
``` 

### `editable = false` (상품 별점, 리뷰 상세)
* 사용 예시
```typescript
<StarRating rating={3} />
```
- 위 예시에는 그냥 숫자 3을 전달하고 있는데 나중에 API 연결하면 전달받은 rating data를 넘겨주면 됩니다 !

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-22 06:15 UTC, devwqc requested changes
오오!! 작업이 되게 빠르게 진행됐네요?👍👍👍💯💯💯
선택한 별점을 서버로 보내는 과정에 대해서도 생각해 보면 좋을 거 같아요!

2024-05-22 06:15 UTC, devwqc commented on src/components/review/StarRating.tsx
> +  };
❓혹시 `editable`로 별점을 선택하고 리뷰를 작성할 때 사용처에서 선택한 별점의 값을 꺼내오는 방법이 있을까요?

2024-05-22 06:26 UTC, Seoin02 approved these changes
👍🏻 저도 얼른 올려야겠군요ㅎㅎ 고생하셨습니다

2024-05-22 06:26 UTC, Seoin02 commented on package.json
> +    "react-icons": "^5.2.1"
💬 사용한 라이브러리 노션 기술스택에 정리부탁드려용

2024-05-22 06:26 UTC, Seoin02 commented on src/components/review/StarRating.tsx
> +        <Star key={i} selected={stars > i} onSelect={() => handleSelect(i)} />
👍🏻 key 준 거 넘 죠습니다

2024-05-22 06:44 UTC, minyoung0503 commented on src/components/review/StarRating.tsx
> +  };
흠 고민해보겠습니다 !!!!

2024-05-22 07:20 UTC, minyoung0503 commented on src/components/review/StarRating.tsx
> +  };
[9f0d5fc](https://github.com/Together-3team/petFrontend/pull/12/commits/9f0d5fcc6b047ab471a03d4e197eedebd96cb4a7)

나중에 서버로 보내기 위해 별점을 사용처에서 관리할 수 있도록 수정했습니다 !

2024-05-22 11:59 UTC, devwqc approved these changes

2024-05-23 00:00 UTC, Seoin02 approved these changes

2024-05-23 03:15 UTC, merged