[서인] my order 페이지 / UI 구현
Together-3team/petFrontend pull request #123
Opened 2024-06-08 14:37 UTC by Seoin02

## 🔥관련 이슈

- #85 

## :grin:주요 변경 사항

- my/order 페이지 엠티뷰 UI 구현
- my/order 페이지 UI 구현
- 무한 스크롤 커스텀 훅 구현
- Card, Tag, Button 스타일 추가

## 📄스크린샷
![주문 내역 없는 my:order 페이지 UI](https://github.com/Together-3team/petFrontend/assets/144193370/e788933c-833f-4a4d-88a4-a5e229704c13)
![my:order 페이지](https://github.com/Together-3team/petFrontend/assets/144193370/dd4c25f8-2ca5-4eab-b806-76cc9fca92af)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- 무한 스크롤 커스텀 훅은 API 연결 후 테스트 해서 보완하겠습니다.
- my/order API 연결 후 데이터 유무에 따라 return 되게 합치겠습니다.
- Card 공통 컴포넌트에 'miniImage' 프롭을 추가해 이미지가 8rem인 주문내역 카드를 만들었습니다.
- Tag 공통 컴포넌트에 medium 사이즈를 추가해 주문내역 카드에 사용했습니다.
- Button 공통 컴포넌트에 small 사이즈, 회색선 하얀 배경, 연한 회색 배경, 분홍선 흰색 배경 스타일을 추가했습니다.

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-08 15:10 UTC, devwqc requested changes
서인님 감사합니다!👍💯👍💯👍💯👍💯

무한 스크롤 훅까지 뚝딱 만드셨네요👍
다른 분들이 작업하신 거 분석하고 반영하느라 쉽지 않았을텐데 고생하셨습니다

2024-06-08 15:10 UTC, devwqc commented on src/pages/my/order/index.tsx
> +      <div>
❗지금 `Header` `div`로 한 번 더 감싸고 있는데 삭제해야 할 거 같아요!
`position: sticky;`의 범위가 `orderLayout`에 걸친게 아니라 `<div>`에 걸쳐서 제대로 동작하지 않네요

2024-06-08 15:10 UTC, devwqc commented on src/components/OrderFilterBar/index.tsx
> +      </button>
💊 `map`으로 작성하면 더 깔끔할 거 같은데 서인님 생각은 어떠신가요?

2024-06-08 15:10 UTC, devwqc commented on src/components/OrderFilterBar/index.tsx
> +  };
💊 필터는 URL 기반으로 상태 관리하면 좋아서 제가 작업하고 있으니 나중에 적용하시면 될 거 같아요!

2024-06-10 00:21 UTC, Seoin02 commented on src/pages/my/order/index.tsx
> +      <div>
flex gap 적용 안되게 하려고 div로 묶었던 것인데 수정했습니다!

2024-06-10 00:22 UTC, Seoin02 commented on src/components/OrderFilterBar/index.tsx
> +  };
감사합니다🙏

2024-06-10 01:57 UTC, Seoin02 commented on src/components/OrderFilterBar/index.tsx
> +      </button>
좋은 의견 감사합니다!! 수정했습니다!

2024-06-10 06:18 UTC, devwqc approved these changes

2024-06-10 07:49 UTC, minyoung0503 approved these changes
고생하셨어요 서인님 👍 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️

2024-06-10 08:31 UTC, merged