[송은] bottomSheet 컴포넌트
Together-3team/petFrontend pull request #132
Opened 2024-06-10 12:24 UTC by q45402sk

## 🔥관련 이슈

- #131 

## :grin:주요 변경 사항

- bottomSheet
- toast와 연결

## 📄스크린샷
![pet-bottomSheet](https://github.com/Together-3team/petFrontend/assets/56138199/a352fdfa-a905-4eec-b696-b335a8aabc2d)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-10 12:50 UTC, devwqc approved these changes
송은님 감사합니다!👍💯👍💯👍💯👍💯👍💯

나머지 작업은 제가 마무리 지을게요!
다른 작업들 많이 남으셨으니까 그쪽으로 넘어가시면 될 거 같아요👍

2024-06-10 12:51 UTC, Seoin02 requested changes
❤️송은님, (봉찬님과 함께) 넘 고생 많았습니다ㅠㅠ 진짜... 주말 내내 고민하시던데 결국 해내셨군요! 드래그앤 드롭이 안 그래도 어렵다고 들었는데, 드래그로 닫는 게 참 어렵네요ㅜㅜ 잘 쓰겠습니다! 감사합니다👍🏻💯💛💪🏻👍🏻💯💛💪🏻👍🏻💯💛💪🏻👍🏻💯💛💪🏻👍🏻💯💛💪🏻

2024-06-10 12:51 UTC, Seoin02 commented on src/components/common/Modal/BottomSheet/BottomSheet.module.scss
> +  bottom: -1000px;
❓오... 이건 뭔가요??ㅋㅋㅋㅋㅋㅋ

2024-06-10 12:51 UTC, Seoin02 commented on src/pages/test/bottom-sheet/index.tsx
> +        <span>Content아아아아아아아아아아아아아아아아아아아아ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ</span>
💬지침이 느껴집니다ㅠㅠ 정말 고생 많으셨어여ㅠㅠㅠㅠㅠㅠ

2024-06-10 12:51 UTC, Seoin02 commented on src/components/common/Modal/BottomSheet/Header.tsx
> +const Header = () => {
❗️함수선언식으로 바꾸면 좋을 것 같습니다

2024-06-10 12:51 UTC, Seoin02 commented on src/hooks/useBottomSheet.ts
> +    const shouldClose = info.point.y > 20 || (info.point.y >= 0 && info.point.y > 45);
👍🏻와 드래그로 닫아야 하니 고려할게 많아지는군요!

2024-06-10 12:51 UTC, Seoin02 commented on src/components/common/Modal/BottomSheet/index.tsx
> +import { Dispatch, ReactNode, SetStateAction, useEffect, useRef, useState } from 'react';
❗️사용예시 적어주시면 감사할 것 같습니다^0^

2024-06-11 05:05 UTC, minyoung0503 approved these changes
송은님 고생하셨어요 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2024-06-11 05:07 UTC, q45402sk commented on src/components/common/Modal/BottomSheet/BottomSheet.module.scss
> +  bottom: -1000px;
바텀시트를 위로 드래그 하면 뒷 배경이 보이는데 그거 방지하려고 넣었습니다!

2024-06-11 05:07 UTC, q45402sk commented on src/components/common/Modal/BottomSheet/Header.tsx
> +const Header = () => {
네 변경했습니다!

2024-06-11 05:07 UTC, q45402sk commented on src/components/common/Modal/BottomSheet/index.tsx
> +import { Dispatch, ReactNode, SetStateAction, useEffect, useRef, useState } from 'react';
네 수정했습니다!

2024-06-13 09:28 UTC, Seoin02 approved these changes

2024-06-13 10:35 UTC, merged