[지원] Button 컴포넌트 구현
Together-3team/petFrontend pull request #14
Opened 2024-05-22 09:56 UTC by seolsis

## 🔥관련 이슈

- #13 

## :grin:주요 변경 사항

- 버튼 공통 컴포넌트 구현
- 버튼 사이즈, 배경색 분리

## 📄스크린샷
![image](https://github.com/Together-3team/petFrontend/assets/88234067/e8fdeec3-4160-4b51-9a64-37b76086c87c)
![image](https://github.com/Together-3team/petFrontend/assets/88234067/a245a9de-1c7b-4ea3-b269-30c163b4f273)
![image](https://github.com/Together-3team/petFrontend/assets/88234067/36c74e08-8c90-4c00-9124-c56d6446bf4b)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- 사용법

![image](https://github.com/Together-3team/petFrontend/assets/88234067/2ccc9483-0edc-40b0-b9dd-5f81be715ff6)
``` javascript
<Button size="large" text="Submit" backgroundColor="#545454" />
```
![image](https://github.com/Together-3team/petFrontend/assets/88234067/bf56c19b-741a-44e9-bf58-f66ea83210d7)
``` javascript
<Button size="medium" text="취소" backgroundColor="#FFFFFF" />
```
![image](https://github.com/Together-3team/petFrontend/assets/88234067/efbc5123-2ea6-4ba4-a882-b7c859d2ee7a)
``` javascript
<Button size="medium" text="탈퇴" backgroundColor="#545454" />
```

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-22 11:58 UTC, devwqc requested changes
고생하셨어요!
되게 뚝딱 잘 만드시네요?! 💯💯💯

2024-05-22 11:58 UTC, devwqc commented on src/components/common/Button/index.tsx
> +        {text}
💊일반적으로 `button`은 `<button>버튼</button>` 처럼 `close tag`가 존재하는 방식이 나을 거 같아요!
`text props`를 따로 받는 것보다 `children`을 활용하면 조금 더 `button`스럽게 사용할 수 있을 거 같은데 지원님 생각은 어떠실까요?
```ts
<button text="버튼" />
<button>버튼<button>
```

2024-05-22 12:00 UTC, seolsis commented on src/components/common/Button/index.tsx
> +        {text}
넵 저도 그 부분 고려해봤는데 아직 children에 대한 이해가 부족하다고 느껴서 추후에 고쳐보겠습니다 피드백 감사합니다!!!

2024-05-23 00:05 UTC, Seoin02 approved these changes

2024-05-23 00:05 UTC, Seoin02 commented on src/components/common/Button/index.tsx
> +  size: 'large' | 'medium';
💬 오 이렇게 타입을 지정할 수 있군요??

2024-05-23 02:30 UTC, minyoung0503 approved these changes
고생하셨어요 지원님 !!!!!!! 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2024-05-23 08:55 UTC, seolsis commented on src/components/common/Button/index.tsx
> +        {text}
@devwqc children 활용하여 수정하였습니다! 확인하시고 approve 부탁드립니당

2024-05-23 09:01 UTC, devwqc approved these changes

2024-05-23 09:25 UTC, merged