[서인] accessToken으로 인증 처리
Together-3team/petFrontend pull request #140
Opened 2024-06-13 08:13 UTC by Seoin02

## 🔥관련 이슈

- #100 

## :grin:주요 변경 사항

- 구글, 카카오 oauth 로그인 구현
- accessToken 쿠키에 저장
- 로그인 상태 확인하는 useAuth 커스텀 훅 구현
- axiosIntercepter 구현 => axios 통신 응답값에 따라 상태 표시 / accessToken 만료시 refreshToken 갱신

## 📄스크린샷

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-13 08:31 UTC, devwqc requested changes
서인님 감사드립니다~👍🥇👍🥇👍🥇👍🥇👍🥇

`refreshToken`으로 자동으로 `accessToken` 갱신까지 구현하시다니... 👍

2024-06-13 08:31 UTC, devwqc commented on next.config.mjs
> +  reactStrictMode: false,
❗엄격 모드를 끄신 이유가 있을까요? 웬만하면 엄격 모드를 꺼야하는 상황은 피하는 게 좋은 거 같아서요!

2024-06-13 08:31 UTC, devwqc commented on src/hooks/useAuth.ts
> +  }, []);
❗로그인 여부를 토큰의 존재로만 판단하기에는 토큰에 만료 시간이 있기 때문에 다른 방법이 필요할 거 같아요!

저는 `useAuth` 훅이 단순히 로그인 여부를 알려주는 것보다 사용자 정보를 가져오는 훅으로 변경하면 어떨까 싶어요
사용자 정보를 필요로 하는 곳들이 많이 있고 사용자 정보가 없으면 자연스럽게 로그인 하지 않은 상태니까 로그인 여부도 판단할 수 있어서 더 좋지 않을까 싶습니다! 서인님 생각은 어떠실까요?

2024-06-13 08:31 UTC, devwqc commented on package.json
> +    "cookies-next": "^4.2.1",
❓ 이 패키지를 사용한 곳이 있을까요? 제가 확인할 때는 없는 거 같아서요...!

2024-06-13 08:31 UTC, devwqc commented on src/utils/cookie.ts
> +}
❓제가 `react-cookie`를 사용해본 적이 없는데 지금 SSR, SSG에서 `getCookie`로 쿠키가 정상적으로 받아와질까요?

2024-06-13 08:31 UTC, devwqc commented on src/apis/axiosIntercepter.ts
> +        }
❓보통 `500`번대 에러 상태는 서버 에러인데 권한 없음 상태로 변경 필요하지 않을까요?
보통 권한과 관련된 에러 상태는 `401`, `403`인데 저희 스웨거에서는 `404`를 사용하는 거 같네요...!

2024-06-13 09:14 UTC, Seoin02 commented on next.config.mjs
> +  reactStrictMode: false,
저도 그렇게 생각합니다! 그런데 OAuth 구현 시 인가 코드는 1회성이라 동일한 인가 코드를 두 번 이상 사용하면 에러가 발생합니다. 그래서 함수를 두 번 호출하게 하는 strict 모드를 끌 수 밖에 없었어요...

2024-06-13 09:18 UTC, Seoin02 commented on src/hooks/useAuth.ts
> +  }, []);
refreshToken으로 갱신해주는데도 바꾸는게 나을까요?? 그리고 사용자 정보도 쿠키에 저장할까요?

2024-06-13 09:19 UTC, Seoin02 commented on package.json
> +    "cookies-next": "^4.2.1",
삭제했습니다

2024-06-13 09:23 UTC, Seoin02 commented on src/utils/cookie.ts
> +}
[react-cookie](https://www.npmjs.com/package/react-cookie)를 참고하면 서버사이드에서도 사용가능합니다

2024-06-13 09:24 UTC, Seoin02 commented on src/apis/axiosIntercepter.ts
> +        }
<img width="331" alt="스크린샷 2024-06-13 오후 5 34 57" src="https://github.com/Together-3team/petFrontend/assets/144193370/59628c67-c99d-4004-bf2f-76f39f178253">
토큰 만료 시 500에러를 띄워주는 거 아닌가요?

2024-06-13 12:08 UTC, seolsis commented
우아 어려운거 하시느라 고생 많으셨어요 서인님 👏🏻👏🏻👏🏻🐶

2024-06-13 12:08 UTC, seolsis approved these changes
우아 어려운거 하시느라 고생 많으셨어요 서인님 👏🏻👏🏻👏🏻🐶

2024-06-13 12:31 UTC, devwqc commented on src/apis/axiosIntercepter.ts
> +        }
> 토큰 만료 시 500에러를 띄워주는 거 아닌가요?

그건 `refreshToken`을 갱신할 때 API 응답 같고, 제 생각에는 만들어주신 `axios instance`로 요청 보냈을 때 500번 에러가 발생하면 `interceptor`가 `refreshToken`으로 `newAccessToken` 받고 다시 요청 보내는 로직으로 보이고 있거든요

제가 실제로 로그인을 요구하는 API에 로그인 없이 API 호출 했을 때 다음과 같이 401 에러가 발생했습니다!

![스크린샷 2024-06-13 212632](https://github.com/Together-3team/petFrontend/assets/98067115/2c82b274-439a-4bea-bbc3-afd7398bbcea)

2024-06-13 12:31 UTC, devwqc commented on src/hooks/useAuth.ts
> +  }, []);
> refreshToken으로 갱신해주는데도 바꾸는게 나을까요?? 그리고 사용자 정보도 쿠키에 저장할까요?

갱신해 주더라도 어떤 API 호출을 해야 인터셉터 통해서 갱신하는 거지 홈페이지에서 아무런 API도 호출하지 않은 상태에선 `accessToken`의 여부로 로그인 여부를 체크하기에는 조금 무리가 있는 거 같아요...!

사용자 정보는 쿠키에 저장하지 말고 `useAuth` 훅으로 사용자 정보를 가져오면 될 거 같아요~
사용자 정보 또는 로그인 여부를 필요로 하는 곳에서 `useAuth` 호출해서 사용하면 되니까

2024-06-13 12:53 UTC, minyoung0503 approved these changes
고생하셨어요 서인님 👍🙇🏻‍♀️🤍👍🙇🏻‍♀️🤍👍🙇🏻‍♀️🤍👍🙇🏻‍♀️🤍

2024-06-14 05:35 UTC, Seoin02 commented on src/apis/axiosIntercepter.ts
> +        }
수정했습니다

2024-06-14 13:34 UTC, Seoin02 commented on src/hooks/useAuth.ts
> +  }, []);
반영했습니다.

2024-06-14 14:09 UTC, devwqc requested changes

2024-06-14 14:09 UTC, devwqc commented on src/hooks/useAuth.ts
> +  };
💊 `userData`도 내보내면 좋을 거 같은데 서인님 생각은 어떠실까요??

2024-06-14 14:09 UTC, devwqc commented on src/pages/auth/google/callback.tsx
> +    return response.data;
❓`authAxiosInstance`에 `baseUrl`이 등록 됐는데 앞에 `${API_BASE_URL}` 없어도 되지 않나요?

2024-06-14 14:09 UTC, devwqc commented on src/pages/auth/google/callback.tsx
> +      queryClient.invalidateQueries({ queryKey: ['googleAuth'] });
💊 queryKey로  `googleAuth`를 `get`으로 캐싱 사용하는 곳이 있나요? 없으면 삭제해도 될 거 같습니다...! 카카오도 똑같이 되어 있더라구요

2024-06-14 14:14 UTC, Seoin02 commented on src/hooks/useAuth.ts
> +  };
죠습니다

2024-06-14 14:17 UTC, Seoin02 commented on src/pages/auth/google/callback.tsx
> +    return response.data;
수정했습니다

2024-06-14 14:17 UTC, Seoin02 commented on src/pages/auth/google/callback.tsx
> +      queryClient.invalidateQueries({ queryKey: ['googleAuth'] });
수정했습니다

2024-06-14 14:21 UTC, devwqc approved these changes

2024-06-14 14:22 UTC, merged