[송은] deliveryEditPage
Together-3team/petFrontend pull request #153
Opened 2024-06-16 07:44 UTC by q45402sk

## 🔥관련 이슈

- #152 

## :grin:주요 변경 사항

- 배송지 수정 페이지
-

## 📄스크린샷
![pet-deliveryEditPage](https://github.com/Together-3team/petFrontend/assets/56138199/1001c2aa-cc23-45bf-bd73-a4f8228ad0ab)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-16 08:23 UTC, devwqc requested changes
송은님 감사합니다!!👍👍👍👍💯💯💯💯💯

배송지 추가 페이지가 생각보다 되게 빠르게 나왔네요?!
`input` 요소가 많아서 복잡했을 거 같은데 잘하셨고 `hook-form` 사용 개선은 프로젝트 종료 후에 진행해도 좋을 거 같아요~

지금은 저장 버튼에 `isValid` 처리만 추가하면 좋을 거 같습니다!👍

2024-06-16 08:23 UTC, devwqc commented on src/components/payment/AddressInput.tsx
> +  const [address, setAddress] = useState('');
💊`DeliveryEditPage`에서 42번 라인에 `<FormProvider {...methods}>`로 `useForm`의 메소드를 넘기고 있어서 `register`를 따로 받을 필요가 없다고 느껴집니다. 추가적으로 `setValue`도 필요 없을 거 같아요!

그리고 `hook-form`으로 `input`을 관리하니까 value state도 필요 없을 거 같습니다!

작업하실 부분이 많으시면 우선 넘어가시고 나중에 개선하는 것도 좋을 거 같아요~

2024-06-16 08:23 UTC, devwqc commented on src/pages/payment/delivery/edit/index.tsx
> +            </Button>
💊 `hook-form`에서 `isValid` 여부로 `Button`을 `disabled` 처리하는 것도 좋을 거 같아요~

2024-06-16 11:06 UTC, Seoin02 approved these changes
👍🏻송은님 배송지 입력 폼 구현하느라 고생많으셨습니다! 주소 불러오는 API도 붙이고, 멋져요!!! 주말에 정말 고생많으셨습니다!💘💘💘💘💘💘💘💘💘💘💘

2024-06-16 11:06 UTC, Seoin02 commented on src/components/common/Input/index.tsx
> +          autoComplete={autoComplete}
👍🏻오 이거 좋네요 이후에 ...rest로 input 속성을 다 받아오게 input 컴포넌트 리팩토링 하는 것도 고민해봐야겠어요

2024-06-16 11:06 UTC, Seoin02 commented on src/components/payment/AddressInput.tsx
> +            theme={themeObj}
❓DaumPostCode를 쓰려면 인라인으로 css를 넣어줘야 하는 건가요??

2024-06-16 11:06 UTC, Seoin02 commented on src/utils/deliveryFormSchema.ts
> +  name: Yup.string()
👍🏻오호 정규식을 잘 사용해서 FormSchema를 잘 정의하셨군요!

2024-06-17 07:42 UTC, q45402sk commented on src/components/payment/AddressInput.tsx
> +            theme={themeObj}
DaumPostCode에 element style로 width랑 height가 기본값으로 들어가 있어서 module css 적용이 안 되더라구요 그래서 width랑 height만 인라인으로 넣어주었습니다!

2024-06-17 07:45 UTC, q45402sk commented on src/pages/payment/delivery/edit/index.tsx
> +            </Button>
isValid 추가하고 우편번호 에러 뜨는 부분에 문제가 있어서 그냥 우편 번호랑 주소 부분은 readOnly 추가하고 입력값 없어도 에러 안 뜨게 했습니다! 어차피 입력값 없으면 버튼이 비활성화 상태가 돼서 이렇게 처리했어요

2024-06-17 10:50 UTC, devwqc approved these changes

2024-06-18 02:56 UTC, merged