[송은] 카드 글씨 흐르는 효과 제거
Together-3team/petFrontend pull request #159
Opened 2024-06-17 08:49 UTC by q45402sk

## 🔥관련 이슈

- #158 

## :grin:주요 변경 사항

- 카드 글씨 흐르는 효과 제거
-

## 📄스크린샷
![pet-fixcard](https://github.com/Together-3team/petFrontend/assets/56138199/009aa7ef-9819-4c8c-8343-79cd4a9da26d)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)
서인님이 수정하신 부분 중에서
module.scss애서 title 부분을 스크린샷처렴 변경하였습니다. (글씨가 흐트러져서 data-direction='row'를 뺐어요)

-변경
![스크린샷 2024-06-17 172309](https://github.com/Together-3team/petFrontend/assets/56138199/3df6baa9-e237-4c34-8e90-b9cda9f6a552)

-변경후
![스크린샷 2024-06-17 172320](https://github.com/Together-3team/petFrontend/assets/56138199/f00a7af5-a6ac-4584-b6a2-8ffbeb06c083)

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-17 08:52 UTC, seolsis approved these changes
구현하느라 고생하셨는데 아쉬워요 🥲 그래도 정말 좋은 아이디어였어요 수정하느라 수고하셨습니다 🙇🏻‍♀️🙇🏻‍♀️

2024-06-17 10:11 UTC, Seoin02 approved these changes
👍🏻덕분에 다양한 css 애니메이션을 경험했습니다 송은님 짱짱걸 최고!!!

2024-06-17 10:11 UTC, Seoin02 commented on src/components/common/Card/index.tsx
> +    <Link href={`/product/${title}`} className={cx('card')} as="image" data-direction={direction} data-size={size}>
❓as가 무슨 역할을 하나요? 검색해도 잘 안나오네요ㅠㅠ

2024-06-17 10:49 UTC, devwqc requested changes
송은님 감사드립니다!!👍💯🥇👍💯🥇👍💯🥇👍💯🥇

자식 군대 보내는 마음처럼 가슴 아프셨을 거 같은데
백업 잘 하셨으니까 저도 나중에 사용하겠습니다!👍

2024-06-17 10:49 UTC, devwqc commented on src/components/common/CardFlow/Card.module.scss
> +}
😢 아쉬움에 `CardFlow`로 백업하신 건가요...? 저도 정말 아쉽네요...

2024-06-17 10:49 UTC, devwqc commented on src/components/common/Card/Card.module.scss
> +  -webkit-box-orient: vertical;
💊 디자인 시안 보니까 ...이 바닥에 붙어있는데 송은님이 만들어주신 ...은 가운데에 위치하네요...?

[송은님이 만드신 카드]
![스크린샷 2024-06-17 194513](https://github.com/Together-3team/petFrontend/assets/98067115/320550dc-5f38-471f-b502-cbb323472ae7)

[디자인 시안 카드]
![스크린샷 2024-06-17 194539](https://github.com/Together-3team/petFrontend/assets/98067115/7b4b2668-d745-4149-8ec6-06b0043f603a)

2024-06-18 02:22 UTC, q45402sk commented on src/components/common/Card/index.tsx
> +    <Link href={`/product/${title}`} className={cx('card')} as="image" data-direction={direction} data-size={size}>
우선 next Link 컴포넌트의 as는 브라우저 url 주소창에 보일 값을 지정해주는 데코레이터입니다.
- https://nextjs.org/docs/api-reference/next/link
라고 하는데 이게 왜 들어갔는지 모르겠네요 빼겠습니다!

2024-06-18 02:22 UTC, q45402sk commented on src/components/common/CardFlow/Card.module.scss
> +}
네 맞습니다...

2024-06-18 02:47 UTC, devwqc approved these changes

2024-06-18 03:04 UTC, merged