[지원] Dropdown 기능 구현
Together-3team/petFrontend pull request #16
Opened 2024-05-22 14:01 UTC by seolsis

## 🔥관련 이슈

- #15 
## :grin:주요 변경 사항

- react-select 라이브러리 사용
- Dropdown placeholder 설정
- Dropdown에서 옵션을 선택하면 placeholder 값에서 해당 옵션으로 값이 변경됨

## 📄스크린샷
![옵션선택](https://github.com/Together-3team/petFrontend/assets/88234067/20b0bfe8-0dc6-47c2-b9f4-b91ff8058c6a)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- 사용법
```javascript
const options = [
    { value: 'option1', label: 'option1' },
    { value: 'option2', label: 'option2' },
    { value: 'option3', label: 'option3' },
  ];
return (
    <>
      <Dropdown options={options} placeholder="상품 옵션을 선택해 주세요" />
    </>
  );
```

options 배열을 만들고 Dropdown prop의 값으로 만든 options 배열을 주시면 됩니다. 
placeholder도 필요하신대로 설정하시면 되고 기본 값은 상품 옵션을 선택해 주세요로 설정하였습니다.

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-22 14:19 UTC, devwqc requested changes
지원님 고생하셨어요!! 👍👍👍🤭🤭🤭
드롭다운 구현 어렵다고 생각하고 있었는데 어떻게 이렇게 빠르게 작업이 되는 거죠?!

2024-05-22 14:19 UTC, devwqc commented on src/components/common/Dropdown/index.tsx
> +    </>
❓`option`을 선택했을 때 발생할 수 있는 `trigger`나 선택한 `option`의 값을 서버로 전달하는 방법이 따로 보이지 않는데 맞을까요?!

만약 그렇다면 이런 경우에는 rest props랑 hidden input으로 처리해도 괜찮을 거 같아요👍
```ts
<>
  <input type="hidden" value={selectedOption.value} {...rest} />
  <Select
    className={styles.dropdown}
    options={options}
    value={selectedOption}
    onChange={handleChange}
    placeholder={placeholder || '상품 옵션을 선택해 주세요'}
  />
</>
```

2024-05-23 00:07 UTC, Seoin02 approved these changes
👍🏻 와 진짜 뚝딱뚝딱 잘 만드시네요 타입도 잘 쓰시는 것 같아요!

2024-05-23 08:46 UTC, seolsis commented on src/components/common/Dropdown/index.tsx
> +    </>
@devwqc 수정완료했는데 확인 부탁드립니다! 그리고 내용 추가했는데 instanceId 쓴 부분도 같이 봐주시면 감사하겠습니다! 콘솔에 warning이 떠서 instanceId 속성 써서 warning을 없애긴 했는데 값을 저렇게 줘도 되는지 헷갈려요,,

2024-05-23 09:00 UTC, devwqc commented on src/components/common/Dropdown/index.tsx
> +    </>
> @devwqc 수정완료했는데 확인 부탁드립니다! 그리고 내용 추가했는데 instanceId 쓴 부분도 같이 봐주시면 감사하겠습니다! 콘솔에 warning이 떠서 instanceId 속성 써서 warning을 없애긴 했는데 값을 저렇게 줘도 되는지 헷갈려요,,

죄송해요... `react-select`는 잘 몰라서 저렇게 처리하면 될 줄 알았는데 찾아보니까 저게 보편적인 방식은 아닌가봐요!
그래서 `instanceId` 경고도 뜬 거 같고 우선은 원래 만들었던 방식으로 가면 될 거 같아요 🙏
[react-select](https://1two13.tistory.com/entry/React-react-select-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%84%9C-select-%EB%A7%8C%EB%93%A4%EA%B8%B0-select-%EC%A0%84%EB%B6%80-%EC%B4%88%EA%B8%B0%ED%99%94%ED%95%98%EB%8A%94-%EB%B2%95)

2024-05-23 09:24 UTC, seolsis commented on src/components/common/Dropdown/index.tsx
> +    </>
@devwqc 원래 방식이라고 하면 hidden input 사용전 말씀하시는거 맞나요??

2024-05-23 09:27 UTC, devwqc commented on src/components/common/Dropdown/index.tsx
> +    </>
> @devwqc 원래 방식이라고 하면 hidden input 사용전 말씀하시는거 맞나요??

넵! `hidden input` 사용하지 않는 것이 `react-select`에서 제공하는 사용법 같아요

2024-05-23 09:34 UTC, seolsis commented on src/components/common/Dropdown/index.tsx
> +    </>
이전 상태로 바꾸었습니다!

2024-05-23 09:38 UTC, devwqc commented on src/components/common/Dropdown/index.tsx
> +    </>
> 이전 상태로 바꾸었습니다!

번거롭게 죄송합니다...! 의견 참고해 주셔서 감사해요👍👍👍👍

2024-05-23 09:38 UTC, devwqc approved these changes

2024-05-23 10:21 UTC, merged