[서인] Onboarding 페이지 / api 연결
Together-3team/petFrontend pull request #162
Opened 2024-06-17 13:20 UTC by Seoin02

## 🔥관련 이슈

- #146 

## :grin:주요 변경 사항

- 회원가입 로직 수정&useAuth 수정
- 회원정보 수정(전화번호)구현
- 회원 탈퇴 구현
- next 미들웨어 세팅

## 📄스크린샷
![회원가입, 탈퇴, 로그인](https://github.com/Together-3team/petFrontend/assets/144193370/429700fa-b86f-441a-9562-3ace96d6678d)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- onboarding에서 반려동물 선택 구현해야합니다...
- my페이지에서 리다이렉트 시 userData 못 불러오는 이슈 해결해야합니다...
- 늦게 구현해서 죄송합니다... 이제 진짜 잘 돌아갑니다...! 그래도 혹시 이슈가 있다면 꼭 알려주시면 감사하겠습니다!

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-17 14:21 UTC, devwqc requested changes
서인님 감사드립니다~👍💯👍💯👍💯👍💯

인가 관련한 부분이 어려워서 리액트 쿼리도 많이 작성하시고 전체적으로 작업량이 많네요...

2024-06-17 14:21 UTC, devwqc commented on middleware.ts
> +}
❗`middleware` 제대로 작동하시나요? `middleware`는 `pages` 폴더와 같은 라인에 두어야 해요!
저희는 `src`에 `pages`가 있으니까 `src`에 넣으면 될 거 같습니다.

2024-06-17 14:21 UTC, devwqc commented on src/apis/axiosInstance.ts
> +  }
❓`accessToken` 여부만 있으면 되지 않을까 생각이 드는데 `!config.headers.Authorization`를 추가하신 이유가 있을까요?
```suggestion
  if (accessToken) {
    config.headers.Authorization = `Bearer ${accessToken}`;
  }
```

2024-06-17 14:21 UTC, devwqc commented on src/apis/axiosInstance.ts
> +          return authAxiosInstance(originalRequest);
💊 `refreshToken` 갱신할 때 `requestBody`로 `refreshToken` 넣어서 보내는 거 같은데 헤더에 추가하신 이유가 있을까요?

![스크린샷 2024-06-17 230535](https://github.com/Together-3team/petFrontend/assets/98067115/7ee4e551-5a62-44b5-92ad-6b61433bc776)

2024-06-17 14:21 UTC, devwqc commented on src/apis/userApi.ts
> +};
👍 오... 객체로 관리하는 센스 너무 좋네요!!

2024-06-17 14:21 UTC, devwqc commented on src/components/auth/SignupForm/index.tsx
> +          <Button type="submit" size="large" backgroundColor="$color-pink-main">
👍 멘토님 피드백 바로 반영하셨네요~ 👍👍👍

2024-06-17 14:21 UTC, devwqc commented on src/components/common/Button/index.tsx
> +  type?: string;
💬 조금 늦은 감이 없지 않아 있지만 `ComponentPropsWithoutRef<'button'>`으로 타입 확장했으면 `button`의 기본적인 속성들은 모두 지원해서 더 좋았을 거 같긴 하네요...!

2024-06-17 14:21 UTC, devwqc commented on src/components/common/Input/index.tsx
> +  defaultValue?: string;
❓ `defaultValue`를 사용하는 곳이 보이지 않는데 삭제해도 되지 않을까요?

2024-06-17 14:21 UTC, devwqc commented on src/components/common/Nav/Bottom/index.tsx
> +import useAuth from '@/hooks/useAuth';
💊 따로 사용하지 않으시면 `import`문 삭제해도 될 거 같아요~

2024-06-17 14:21 UTC, devwqc commented on src/pages/auth/google/callback.tsx
> +  async function getGoogleAuth(): Promise<GoogleAuthResponse> {
💬 전혀 눈치채지 못했는데 멘토님 눈썰미가 대단하시네요

2024-06-17 16:08 UTC, Seoin02 commented on middleware.ts
> +}
헐 제가 뎁스를 착각했네요ㅠㅠ

2024-06-18 01:58 UTC, Seoin02 commented on src/apis/axiosInstance.ts
> +  }
오홍 그렇네요 수정했습니다

2024-06-18 02:40 UTC, Seoin02 commented on src/apis/axiosInstance.ts
> +          return authAxiosInstance(originalRequest);
수정했습니다

2024-06-18 02:41 UTC, Seoin02 commented on src/components/common/Button/index.tsx
> +  type?: string;
input도 그런 생각이 들어서 어느 정도 작업 마치고 리팩토링 하려고요!

2024-06-18 02:42 UTC, Seoin02 commented on src/components/common/Input/index.tsx
> +  defaultValue?: string;
저 사용하고 있습니다...

2024-06-18 02:43 UTC, Seoin02 commented on src/components/common/Nav/Bottom/index.tsx
> +import useAuth from '@/hooks/useAuth';
삭제했습니다

2024-06-18 03:05 UTC, minyoung0503 approved these changes
서인님 고생하셨어용 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2024-06-18 03:06 UTC, devwqc approved these changes

2024-06-18 04:06 UTC, merged