[지원] bottomModal 컴포넌트 적용
Together-3team/petFrontend pull request #177
Opened 2024-06-18 12:33 UTC by seolsis

## 🔥관련 이슈

- 작성한 이슈를 태그해주세요

## :grin:주요 변경 사항

- bottomModal 컴포넌트 적용
-

## 📄스크린샷
![image](https://github.com/Together-3team/petFrontend/assets/88234067/a71271d0-4b34-43a2-87bc-e095a84434b3)
![image](https://github.com/Together-3team/petFrontend/assets/88234067/730736a1-a305-4b78-a0c3-1ed3ffa360af)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-06-18 13:11 UTC, devwqc requested changes
지원님 감사드립니다~👍👍👍👍👍💯💯💯💯

아까 말씀하셨던 결제 성공 시 query들 뽑아와서 잘 적용하신 거 같네요!👍

2024-06-18 13:11 UTC, devwqc commented on src/apis/authAxiosInstance.ts
> +      'Barear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTcxODcxMDAxMywiZXhwIjoxNzE4NzE3MjEzfQ.4kxGxyk0zBf9Fcto35aMD3waEI3ew7rYJsLokgW3inc',
❓`authAxiosInstance`는 `auth` 쪽에서 사용하는 거라 수정하시면 안 될 거 같은데 따로 사용하시는 곳이 있으신가요?

2024-06-18 13:11 UTC, devwqc commented on src/pages/cart/index.tsx
> +  const [modalContent, setModalContent] = useState<{ type: 'individual' | 'bulk'; id?: number } | null>(null);
👍모달 안에서 동작 필요한 부분에 대해서 고민 많이 하신 거 같아요...👍👍

2024-06-18 13:11 UTC, devwqc commented on src/pages/payment/index.tsx
> +          <Header.Center className={styles.headerName}>결제</Header.Center>
❗PR에 첨부하신 사진으로 봤을 때 장바구니 페이지는 헤더 스타일이 잘 적용된 거 같은데 결제 페이지는 헤더 스타일 적용이 필요할 거 같아요~

2024-06-18 13:18 UTC, Seoin02 requested changes
👍🏻지원님 어려운 부분 맡으셔서 고생 많으십니다ㅠㅠ 감사합니다!

2024-06-18 13:18 UTC, Seoin02 commented on src/apis/authAxiosInstance.ts
> +    Authorization:
❗️지워주시면 좋을 것 같아요~~

2024-06-18 13:18 UTC, Seoin02 commented on src/pages/payment/paymentSuccessByCart.tsx
>  export default function PaymentSuccessByCart() {
❗️함수명 첫 글자 소문자로 바꾸면 좋을 것 같습니다

2024-06-18 15:48 UTC, seolsis commented on src/apis/authAxiosInstance.ts
> +      'Barear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTcxODcxMDAxMywiZXhwIjoxNzE4NzE3MjEzfQ.4kxGxyk0zBf9Fcto35aMD3waEI3ew7rYJsLokgW3inc',
엇 이건 변경하지 말라하셧는데 까먹었어요 죄송합니다 🥲

2024-06-18 15:49 UTC, seolsis commented on src/pages/payment/index.tsx
> +          <Header.Center className={styles.headerName}>결제</Header.Center>
수정 완료했습니다!

2024-06-18 15:49 UTC, seolsis commented on src/apis/authAxiosInstance.ts
> +    Authorization:
넵 죄송합니다 ㅜㅜ 🙇🏻‍♀️

2024-06-18 15:50 UTC, seolsis commented on src/pages/payment/paymentSuccessByCart.tsx
>  export default function PaymentSuccessByCart() {
소문자로 되어있는데 completePayment 얘기하시는거 맞을까요?? 한번 씩 선택한 곳과 다른 곳에 리뷰가 달리는 경우도 있어 여쭤봅니다!

2024-06-19 01:06 UTC, Seoin02 requested changes

2024-06-19 01:06 UTC, Seoin02 commented on src/pages/payment/paymentSuccessByCart.tsx
>  export default function PaymentSuccessByCart() {
PaymentSuccessByCart 이거 말씀드린 거였어요~~

2024-06-19 08:10 UTC, seolsis commented on src/pages/payment/paymentSuccessByCart.tsx
>  export default function PaymentSuccessByCart() {
넵 소문자로 되어있는데 또 인식을 못하는 것 같네요 ㅜ.ㅜ 수정하겠습니다!

2024-06-19 08:17 UTC, minyoung0503 approved these changes
고생하셨어요 지원님 !!!!!!1

2024-06-19 08:22 UTC, devwqc approved these changes

2024-06-19 08:35 UTC, Seoin02 approved these changes

2024-06-19 08:35 UTC, merged