feat: httpClient 생성
Together-3team/petFrontend pull request #3
Opened 2024-05-21 07:48 UTC by seolsis

## 🔥관련 이슈

- 작성한 이슈를 태그해주세요

## :grin:주요 변경 사항
- axiosInstance.ts 파일 생성
- httpClient.ts 파일 생성

## 📄스크린샷

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

2024-05-21 13:30 UTC, devwqc requested changes
지원님 고생 많으셨어요!! 👍👍👍🥇🥇🥇
지금 보면 `axios`가 없어서 빌드 에러 나는데 `axios` 라이브러리만 추가해 주시면 좋을 거 같습니다.

2024-05-21 13:30 UTC, devwqc commented on src/apis/httpClient.ts
> +  }
`get`, `put`에는 `options`로 axios config를 커스텀 할 수 있는 거 같은데 `post`, `del`에는 없어도 될까요??

2024-05-21 13:30 UTC, devwqc commented on src/apis/axiosInstance.ts
> +import axios from 'axios';
❗ `axios` 라이브러리 추가해 주셔야 할 거 같아요!

2024-05-21 14:47 UTC, Seoin02 requested changes
👍🏻 고생많으셨습니다

2024-05-21 14:47 UTC, Seoin02 commented on src/apis/httpClient.ts
> +export const createHttpClient = () => {
❗코드컨벤션 상 함수선언식으로 수정해야 할 것 같습니다~

2024-05-22 02:04 UTC, minyoung0503 approved these changes
고생하셨어요 지원님 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🤍🤍🤍🤍

2024-05-22 06:53 UTC, seolsis commented on src/apis/axiosInstance.ts
> +import axios from 'axios';
설치 완료했습니다!

2024-05-22 06:53 UTC, seolsis commented on src/apis/httpClient.ts
> +export const createHttpClient = () => {
수정 완료했습니다!

2024-05-22 06:55 UTC, seolsis commented on src/apis/httpClient.ts
> +  }
저번 프로젝트에서 데이터를 받아올 때 제 파일에서만 추가적으로 param 입력이 필요해서 써놓은거라서 post, del할 땐 가독성 좋게 그대로 post, del 쓰는 것이 좋을 것 같습니다!

2024-05-22 06:58 UTC, devwqc approved these changes

2024-05-22 10:33 UTC, Seoin02 approved these changes

2024-05-23 02:34 UTC, merged