[서인] refreshToken 교체 이슈 수정
Together-3team/petFrontend pull request #313
Opened 2024-07-17 01:44 UTC by Seoin02

## 🔥관련 이슈

- #308 

## :grin:주요 변경 사항

- 이슈 원인: accessToken 만료 시 refreshToken 교체 후 쿠키에 저장 안해서 403에러 발생
- 이슈 해결: refreshToken을 쿠키에 저장하는 로직 추가

## 📄스크린샷

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-07-17 10:35 UTC, devwqc requested changes
서인님 감사합니다 👍💯👍💯👍💯👍💯👍💯

저는 `SSR`을 사용할 수 있으면 최대한 사용하자는 생각을 지니고 있었어요.
하지만 원티드 프리온보딩에서 `SSR`을 사용해서 야기할 수 있는 문제들을 짚어주면서 모 기업에서 `SSR` 사용으로 서버가 터지는 문제가 발생해서 `SSR`을 최소한으로 사용한다는 말을 듣고 이번 프로젝트에서 리액트 본연에 집중해서 개발했으면 어땠을까?라는 생각도 들게 됐네요! 그러면 `axiosInstance`도 서버, 클라이언트 고민할 필요 없기도 하고.

아무튼! 계속 리팩토링 하시는 모습 정말 보기 좋아요.🍀✨

2024-07-17 10:35 UTC, devwqc commented on src/apis/axiosInstance.ts
> +          document.cookie = `accessToken=${newAccessToken}; path=/`;
❓서버에서 `axiosInstance`를 호출하면 `document` 객체가 존재하지 않아서 문제가 될 거 같은데 괜찮을까요?!

보니까 `axiosInstance` 내부에서 서버, 클라이언트를 분기처리 하는 경우도 있고 서버용 `axiosInstance`, 클라이언트용 `axiosInstance`를 만드는 경우도 있더라구요!

2024-07-17 15:39 UTC, Seoin02 commented on src/apis/axiosInstance.ts
> +          document.cookie = `accessToken=${newAccessToken}; path=/`;
일단 제가 저 로직을 썼을 때 accessToken 만료 시간 후에도 사이트에서 403에러가 뜨진 않더라고요... 그래서 PR을 올린 건데, 말씀하신 내용 더 찾아보겠습니다~~

2024-07-19 14:53 UTC, devwqc approved these changes
고생하셨어요~ 👍💯👍💯👍💯👍💯👍💯

저희 토큰 유지되는 시간 2시간인가요?!

2024-07-19 17:33 UTC, Seoin02 commented
네 accessToken 유지 시간이 2시간입니다

2024-07-19 17:33 UTC, merged