[지원] 장바구니 UI 구현
Together-3team/petFrontend pull request #40
Opened 2024-05-24 12:55 UTC by seolsis

## 🔥관련 이슈

- #27 

## :grin:주요 변경 사항

- 장바구니 UI (장바구니에 상품이 있는 경우만)
- 전체 선택에 따른 개별 선택 상태 변경
- 1 이하로 수량이 내려가지 않도록 설정 

## 📄스크린샷
![cartUI](https://github.com/Together-3team/petFrontend/assets/88234067/5fc55505-fb3a-4610-a357-c7ea44254c26)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- 추후 구현(수정) 사항
1. 상품 목록 아래부터 뜨는 금액 부분 컴포넌트 분리를 하는게 좋을까요?
2. 더미데이터 넣어서 변수로 수정 (이미지, 결제부분)

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-24 13:05 UTC, Seoin02 requested changes
👍🏻 작업속도 정말 빠르시군요! 역시 CTO님 👩‍💻

2024-05-24 13:05 UTC, Seoin02 commented on src/components/cart/Card.tsx
> +import React, { useState } from 'react';
💊 리액트 17버전 이상이면 React를 import 하지 않아도 JSX를 리액트 요소로 변환할 수 있다고 합니다

2024-05-24 13:05 UTC, Seoin02 commented on src/components/cart/Card.tsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
💬 지원님 이 라이브러리 자주 쓰시는군요!ㅋㅋ

2024-05-24 13:05 UTC, Seoin02 commented on src/components/cart/Card.tsx
> +  const addProduct = () => {
❗️함수 선언식으로 바꿔주셔야 할 거 같아요

2024-05-24 13:16 UTC, devwqc requested changes
지원님 고생하셨어요~👍👍👍👍👍💯💯💯💯
고민 많이 하신 흔적이 보이네요! 귀여운 강아지 사진 덕분에 눈 호강 했네요
`package-lock.json`에서 충돌나는 부분은 지원님 꺼로 덮어쓰면 될 거 같아요

2024-05-24 13:16 UTC, devwqc commented on package-lock.json
❗이거 충돌은 `react-hook-form`에서 문제 생겨서 지원님 소스로 덮어쓰면 될 거 같아요!

2024-05-24 13:16 UTC, devwqc commented on public/images/exampleProductImg.jpg
💬이 귀엽고 깜찍한 강아지는 설이인가요?

2024-05-24 13:16 UTC, devwqc commented on src/pages/Cart/index.tsx
> +  const [products, setProducts] = useState(initialProducts.map(product => ({ ...product, isChecked: true })));
👍나중에 서버로 전송할 때 `isChecked` 된 것만 보낼 수 있겠네요~ 너무 좋아요!!

💊 `isChecked` 처럼 수량도 상태에 추가해서 `cart/Card`에서 수량 줄이고 추가할 때도 여기에 수량 반영하면 좋을 거 같은데 지원님 생각은 어떠실까요?

2024-05-25 00:25 UTC, q45402sk approved these changes

2024-05-25 03:47 UTC, seolsis commented on src/components/cart/Card.tsx
> +  const addProduct = () => {
수정 완료했습니다!

2024-05-25 03:47 UTC, seolsis commented on public/images/exampleProductImg.jpg
지피티가 그려준 설이에오

2024-05-25 03:48 UTC, seolsis commented on src/pages/Cart/index.tsx
> +  const [products, setProducts] = useState(initialProducts.map(product => ({ ...product, isChecked: true })));
넵 추가하겠습니다
전달사항에 >>상품 목록 아래부터 뜨는 금액 부분 컴포넌트 분리를 하는게 좋을까요?<< 부분은 어떻게 생각하실까요??

2024-05-25 04:03 UTC, devwqc commented on src/pages/Cart/index.tsx
> +  const [products, setProducts] = useState(initialProducts.map(product => ({ ...product, isChecked: true })));
> 넵 추가하겠습니다 전달사항에 >>상품 목록 아래부터 뜨는 금액 부분 컴포넌트 분리를 하는게 좋을까요?<< 부분은 어떻게 생각하실까요??

이런 경우에서 저는 보통 분리하는 편이에요!

2024-05-25 04:29 UTC, Seoin02 approved these changes

2024-05-27 10:01 UTC, seolsis commented on src/pages/Cart/index.tsx
> +  const [products, setProducts] = useState(initialProducts.map(product => ({ ...product, isChecked: true })));
> 💊 `isChecked` 처럼 수량도 상태에 추가해서 `cart/Card`에서 수량 줄이고 추가할 때도 여기에 수량 반영하면 좋을 거 같은데 지원님 생각은 어떠실까요?
수량도 prop으로 추가했습니다!

2024-05-27 10:26 UTC, devwqc approved these changes

2024-05-27 12:12 UTC, merged