[서인] BottomModal 공통 컴포넌트 구현
Together-3team/petFrontend pull request #41
Opened 2024-05-25 12:33 UTC by Seoin02

## 🔥관련 이슈

- #32 

## :grin:주요 변경 사항

- BottomModal 공통 컴포넌트 구현했습니다.
- 모달 외부를 클릭하면 모달이 닫히게 구현했습니다.
- useModal 커스텀 훅을 만들어 사용처에서 모달 열기와 닫기를 사용할 수 있게 했습니다.

## 📄스크린샷
![BottomModal](https://github.com/Together-3team/petFrontend/assets/144193370/8c8f3b57-a065-4140-93c8-2fefdb28f62a)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- 모달 사용 예시는 pages > text > my.tsx에서 확인할 수 있습니다.
```javascript
1. 사용처에서 import useModal from '@/hooks/useModal';
2. 사용처에서 import ModalPortal from '@/components/Portal';
3.
const [isClient, setIsClient] = useState(false);
  const { modalOpen, handleModalOpen, handleModalClose } = useModal();

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <>
      {isClient && (
        <ModalPortal>
        *모달 사용처 컴포넌트*
            <BottomModal
              className={cx('')}
              modalOpen={modalOpen}
              handleModalOpen={handleModalOpen}
              handleModalClose={handleModalClose}>
              *모달 내부 디자인 추가*
            </BottomModal>
        *모달 사용처 컴포넌트*
        </ModalPortal>
      )}
    </>
  );
```

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-25 12:48 UTC, devwqc requested changes
서인님... 대단합니다! 고생하셨어요~👍👍👍👍👍👍😁😁😁
외부 클릭 시 닫히게 하는 로직은 제가 생각한 부분이 맞다면 정말 신선하고 멋지네요?💯
`Input`들이 `ModalPortal`안에 들어간 부분은 이해가 잘 안 돼서... 혹시 의도하신 부분이 아니라면 `ModalBase`에 배치하는 방법도 고민해 보면 좋을 거 같네요👍

2024-05-25 12:48 UTC, devwqc commented on src/components/Portal.ts
> +export default function ModalPortal({ children }: { children: ReactNode }) {
💊 `common`안에 `Modal` 폴더 만들고 그 안에 넣으면 어떨까요?
그럼 `BottomModal`도 `Modal`안에 들어가면서 조금 더 관심사가 맞을 거 같은 느낌이에요!

2024-05-25 12:48 UTC, devwqc commented on src/components/common/BottomModal/index.tsx
> +        }
👍와... 버블링을 이용한 외부 클릭 시 닫는 로직인가요?
`currentTarget`으로 이벤트 등록한 요소랑 비교하는 로직 같은데 너무 좋은데요??

2024-05-25 12:48 UTC, devwqc commented on src/pages/test/my.tsx
> +  }, []);
❓`isClient`의 역할은 무엇인가요?

2024-05-25 12:48 UTC, devwqc commented on src/pages/test/my.tsx
> +        </ModalPortal>
💊 왜 `ModalPortal` 안에 `Input`들이 들어있는 지 잘 모르겠에요...!
모달은 어차피 `portal`로 고정이니까 `ModalPortal`을 `ModalBase` 안에서의 가장 큰 container로 배치하는 건 어떨까요?

[ModalBase.tsx]
```ts
return (
  <ModalPortal>
    <div className={cx('modalBase', className)}>
      <div className={cx('modalContent')}>{children}</div>
    </div>
  </ModalPortal>
);
```

2024-05-27 04:28 UTC, Seoin02 commented on src/pages/test/my.tsx
> +        </ModalPortal>
오 그렇네요 수정했습니다!

2024-05-27 04:28 UTC, Seoin02 commented on src/pages/test/my.tsx
> +  }, []);
portal을 사용하면서 document에 접근해야 하는데, 이 때 발생하는 에러를 잡기 위해서 사용했습니다. 그런데 삭제해도 에러없이 잘 동작해서 삭제하겠습니다!

2024-05-27 04:28 UTC, Seoin02 commented on src/components/common/BottomModal/index.tsx
> +        }
맞습니다ㅎㅎ

2024-05-27 04:28 UTC, Seoin02 commented on src/components/Portal.ts
> +export default function ModalPortal({ children }: { children: ReactNode }) {
네 반영했습니다

2024-05-27 04:30 UTC, q45402sk approved these changes

2024-05-27 04:56 UTC, minyoung0503 approved these changes
고생하셨어요 서인님 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2024-05-27 05:07 UTC, devwqc approved these changes

2024-05-27 05:07 UTC, merged