[서인]구글 로그인 요청
Together-3team/petFrontend pull request #57
Opened 2024-05-28 09:12 UTC by Seoin02

## 🔥관련 이슈

- #55 

## :grin:주요 변경 사항

- 구글 로그인 요청

## 📄스크린샷
![구글 로그인 요청](https://github.com/Together-3team/petFrontend/assets/144193370/e6917f66-0480-4179-ab6b-cdf28fb1f59b)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-28 15:05 UTC, devwqc requested changes
서인님 감사합니다❗👍 👍 👍 👍 👍 💯💯💯💯

구글 OAuth까지 되게 빠르게 하셨네요?
저는 접속해 보니까 액세스 차단 됐다는데 미리보기 url이 구글 API에 등록되지 않아서 발생하는 문제가 맞을까요?
만약 맞다면 따로 조치하실 필요는 없습니다!

2024-05-28 15:05 UTC, devwqc commented on src/constants/oAuth.ts
> +export const GOOGLE_AUTH_URL = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${GOOGLE_CLIENT_ID}&redirect_uri=${REDIRECT_URL}&response_type=code&scope=email profile`;
👍`constants` 폴더 사용해서 정리해둔 거 너무 좋네요!!

2024-05-28 15:05 UTC, devwqc commented on src/components/auth/Login/GoogleLogin.tsx
> +      </Link>
![스크린샷 2024-05-29 000209](https://github.com/Together-3team/petFrontend/assets/98067115/232720eb-cf52-4d37-8a52-732de8bf7ef0)

❓저는 액세스 차단 됐다고 나오는데 추가적인 세팅이 필요한 부분일까요?

2024-05-29 01:35 UTC, Seoin02 commented on src/components/auth/Login/GoogleLogin.tsx
> +      </Link>
일단 리디렉션 URI에 미리보기 링크 등록해뒀는데 이게 원인이 맞는지 확인해볼게용

2024-05-29 03:23 UTC, minyoung0503 approved these changes
고생하셨어요 서인님  🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ !~!~!~!

2024-05-29 04:48 UTC, Seoin02 commented on src/components/auth/Login/GoogleLogin.tsx
> +      </Link>
구글 OAuth 2.0 리디렉션 URI를 쓸 때 도메인 소유 여부가 중요하다고 합니다. 그런데'https://pawing-market-68pxrxk3j-devwqcs-projects.vercel.app/test/my'은 Vercel에서 제공하는 서브 도메인으로, 일반적으로 사용자가 소유한 도메인으로 간주되지 않아 리디렉션 URI로 사용하는 것은 구글의 규정을 위반할 가능성이 크다고 합니다! 그래서 localhost로만 돌아가는 것 같아요...

2024-05-29 05:42 UTC, devwqc approved these changes

2024-05-29 05:46 UTC, merged