[송은] Card 컴포넌트
Together-3team/petFrontend pull request #58
Opened 2024-05-28 09:15 UTC by q45402sk

## 🔥관련 이슈

- #23 

## :grin:주요 변경 사항

- 카드 컴포넌트 구현
- 태그 컴포넌트 수정

## 📄스크린샷

![pet-card1](https://github.com/Together-3team/petFrontend/assets/56138199/ee21d387-a4d0-4ffa-be05-2502d19b538d)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- pages/ test/ card 부분에 사용 예시 있습니다. 
- 늦어서 죄송합니다ㅠㅠ

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-28 09:36 UTC, devwqc requested changes
송은님 감사합니다!! 👍👍👍👍👍😁😁😁

`Card`가 여러 조건이 많아서 어려웠겠네요...
말씀하신 글자 흐르는 거 적용된 거 보니까 되게 예뻐요 고생하셨어요!!

2024-05-28 09:36 UTC, devwqc commented on src/components/common/Card/index.tsx
> +        }}>
❗지금 `inline-style`이 너무 많이 사용되고 있는데 `className`으로 할 수 있는 건 바꾸는 게 좋을 거 같아요

2024-05-28 09:36 UTC, devwqc commented on src/components/common/Card/index.tsx
> +          reviewCount !== undefined && (
❓❗`stock`이랑 `reviewCount`랑 조건문이 같이 존재하는 이유가 있을까요? 의도가 아니면 수정 필요할 거 같아요!

그리고 `stock`, `reviewCount`가 옵셔널 값이여서 기본값으로 `null` 처리하면 `undefined` 조건은 검사하지 않아도 될 거 같은데 송은님은 어떻게 생각하시나요?

2024-05-28 09:42 UTC, Seoin02 requested changes
👍🏻송은님 코드 곳곳에서 고생한 흔적이 엄청 느껴집니다ㅠㅠ Card 공통 컴포넌트가 제일 까다로운 것 같은데 구현하느라, 상품명 흐름 처리하시느라 고생 많으셨습니다💯💯💯💯💛💛💛💛💛

2024-05-28 09:42 UTC, Seoin02 commented on src/components/common/Card/Card.module.scss
> +@keyframes move-words {
❓오 이게 흐르는 효과인가요?? mix-in으로 재사용하긴 어려울까요?

2024-05-28 09:42 UTC, Seoin02 commented on src/components/common/Card/Card.module.scss
> +  margin: 8px 0 6px;
❓드문드문 px를 쓴 이유가 있을까요?

2024-05-28 09:42 UTC, Seoin02 commented on src/components/common/Card/index.tsx
> +type ProductInfo = {
💬송은님은 interface보다 type을 선호하시나요?? 이유가 궁금합니다

2024-05-28 09:42 UTC, Seoin02 commented on src/components/common/Card/index.tsx
> +          stock !== null &&
❓null과 undefined를 다 비교하는 이유가 있을까요?

2024-05-28 09:42 UTC, Seoin02 commented on src/components/common/Tag/index.tsx
> +      className={styles.tag}
❓오잉 여긴 classnames를 안 쓰셨군요??

2024-05-28 09:46 UTC, devwqc commented on src/components/common/Card/index.tsx
> +          reviewCount !== undefined && (
보니까 기본 값으로 `null` 주지 말고 `0`으로 줘서 `undefined`, `null` 체크 둘 다 안 해도 괜찮을 거 같은데 어떻게 생각하시나요?!

2024-05-29 03:25 UTC, minyoung0503 approved these changes
고생하셨어요 송은님 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ !!!!!!!!!!

2024-05-29 03:25 UTC, minyoung0503 commented on src/components/common/Card/index.tsx
> +  //title이 큰 카드, 작은 카드 각각의 너비를 초과하면 글씨가 흐르도록 함
👍 주석덕분에 이해하기 쉬웠어요 !!!!!

2024-05-29 06:43 UTC, q45402sk commented on src/components/common/Card/index.tsx
> +        }}>
다 조건문이 들어가서 어쩔 수가 없는 것 같아요ㅜㅜ 속성 하나는 scss 파일로 옮겼습니다!

2024-05-29 06:44 UTC, q45402sk commented on src/components/common/Card/index.tsx
> +          reviewCount !== undefined && (
생각해보니까 상품이 품절일 때 고려를 안했더라구요 말씀해주신 거 반영해서 수정했습니다!

2024-05-29 06:46 UTC, q45402sk commented on src/components/common/Card/Card.module.scss
> +  margin: 8px 0 6px;
실수로 썼는데 수정했습니다!

2024-05-29 06:46 UTC, q45402sk commented on src/components/common/Card/index.tsx
> +type ProductInfo = {
type으로 컨벤션을 맞춘 줄 알았어요 수정했습니다!

2024-05-29 06:47 UTC, q45402sk commented on src/components/common/Card/index.tsx
> +          stock !== null &&
stock이랑 reviewcount가 null이 될지 undefined가 될지 모르겠어서 그렇게 썼는데 수정했습니다!

2024-05-29 06:51 UTC, q45402sk commented on src/components/common/Tag/index.tsx
> +      className={styles.tag}
그러네요 ㅎㅎ 수정했습니다!

2024-05-29 06:51 UTC, devwqc commented on src/components/common/Card/index.tsx
> +        }}>
> 다 조건문이 들어가서 어쩔 수가 없는 것 같아요ㅜㅜ 속성 하나는 scss 파일로 옮겼습니다!

어제 멘토님이 알려주신 `data-` 속성으로 `size`나 `direction` 넣어두면 `inline-style` 사용하지 않아도 될 거 같은데 어떻게 생각하시나요?

2024-05-29 06:53 UTC, Seoin02 commented on src/components/common/Card/Card.module.scss
> +@keyframes move-words {
다른 데서 안 쓰이면 mix-in 안해도 될 것 같습니다ㅎㅎ

2024-05-29 06:54 UTC, Seoin02 approved these changes

2024-05-29 07:03 UTC, q45402sk commented on src/components/common/Card/Card.module.scss
> +@keyframes move-words {
네 min-in으로 만들어보긴 했는데 쉽게 재사용할 수 있을지는 잘 모르겠네요,,,

2024-05-29 15:04 UTC, q45402sk commented on src/components/common/Card/index.tsx
> +        }}>
반영했습니다 정말 좋은 방법인 것 같아요!

2024-05-29 15:06 UTC, devwqc commented on src/components/common/Card/index.tsx
> +        }}>
> 반영했습니다 정말 좋은 방법인 것 같아요!

오!! `data-` 반영하니까 되게 깔끔해졌어요👍👍👍👍

2024-05-30 08:09 UTC, devwqc approved these changes

2024-05-30 08:38 UTC, merged