[지원] 장바구니 css 적용
Together-3team/petFrontend pull request #59
Opened 2024-05-28 10:58 UTC by seolsis

## 🔥관련 이슈

- 장바구니 css 적용 
- 할인율 계산 오류 수정

## :grin:주요 변경 사항

- 하단 결제하기 버튼 추가
-

## 📄스크린샷
![cart_css_](https://github.com/Together-3team/petFrontend/assets/88234067/2ecd1a3e-1eff-4ce3-9670-d6ea670c0297)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

-
-

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-28 14:55 UTC, devwqc requested changes
지원님 감사합니다 👍👍👍🤭🤭🤭🥇

수량에 따른 가격 변동되는 작업은 아직 진행되지 않은 거 같아서 그 부분만 작업되면 이제 API 연동만 진행하면 되겠네요~

colors.scss 변수만 적용하면 좋을 거 같아요👍

2024-05-28 14:55 UTC, devwqc commented on src/pages/Cart/index.tsx
> +            <TotalPay totalPrice={totalPrice} totalOriginalPrice={totalOriginalPrice} productCount={productCount} />
👍 오!! 컴포넌트로 따로 분리하니까 페이지 컴포넌트가 가벼워져서 되게 보기 좋은 거 같아요~
💊 url이 대소문자를 구분해서 페이지 경로는 소문자로 통일하면 더 좋을 거 같아요~
`pages/Cart` -> `pages/cart`
테스트 용도로 만드시는 페이지는 `pages/test/~`를 사용하셔도 됩니다

2024-05-28 14:55 UTC, devwqc commented on src/components/cart/Card.module.scss
> +  background-color: #f9fafc;
💊헥사코드로 넣은 색상들 colors.scss에 있는 변수 적용하면 좋을 거 같아요👍

2024-05-29 01:45 UTC, Seoin02 approved these changes
👍🏻고생많으셨습니다 지원님🐾🐾🐾💯💯💯💯💯

2024-05-29 01:45 UTC, Seoin02 commented on src/pages/Cart/index.tsx
>        imageUrl: '/images/exampleProductImg.jpg',
❗️저희 이미지 경로 /assets 쓰기로 했었죠??

2024-05-29 01:45 UTC, Seoin02 commented on src/pages/Cart/index.tsx
> +          지금 구매하면 <span className={styles.pink}>-{totalOriginalPrice - totalPrice}원&nbsp;</span>할인돼요
👍🏻&nbsp;가 줄바꿈이 없는 공백이라니?? 처음 알았어요

2024-05-29 01:45 UTC, Seoin02 commented on src/pages/Cart/index.tsx
>                  key={product.id}
👍🏻key 준 거 굿입니다

2024-05-29 03:28 UTC, minyoung0503 approved these changes
고생하셨어요 지원님 !!~!~!~!  🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️

2024-05-29 07:01 UTC, seolsis commented on src/pages/Cart/index.tsx
>        imageUrl: '/images/exampleProductImg.jpg',
넵 제가 아직 수정을 안햇습니다 ㅜ.ㅜ 바로 수정할게요!

2024-05-29 08:09 UTC, seolsis commented on src/pages/Cart/index.tsx
> +            <TotalPay totalPrice={totalPrice} totalOriginalPrice={totalOriginalPrice} productCount={productCount} />
모든 피드백 다 반영해서 수정 완료했습니다 승인 부탁드려요!  🙇🏻‍♀️🙇🏻‍♀️

2024-05-29 08:16 UTC, devwqc approved these changes

2024-05-29 09:31 UTC, merged