[민영] 리뷰 박스 컴포넌트 구현
Together-3team/petFrontend pull request #60
Opened 2024-05-28 12:34 UTC by minyoung0503

## 🔥관련 이슈

- #33 

## :grin:주요 변경 사항

- 리뷰 박스 컴포넌트 구현
- Textarea -> disabled 상태에서 동적으로 크기 변하는 로직 추가

## 📄스크린샷
<img width="390" alt="스크린샷 2024-05-28 오후 8 05 19" src="https://github.com/Together-3team/petFrontend/assets/155047307/a1babd45-117d-4ba2-8c7a-482ce9a5c915">

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)
- 원래는 defaultProfileImg가 잘 떴는데 develop과 merge하고부터 안 돼요 .. 도와주세요 ㅠ_ㅠ
- textarea 동적으로 크기 변하는 로직은 여기저기 검색 + gpt 도움으로 얼레벌레 구현만 해서 저도 이해가 잘 안 되는 상태에오,, 죄송합니다 ㅠ_ㅠ

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-28 13:29 UTC, seolsis approved these changes
더미데이터가 어쩜 이리 기여울수가.

2024-05-28 14:43 UTC, devwqc requested changes
민영님 감사합니다~👍👍👍👍🤗🤗🤗🤗🤗

제가 조건부로 `svg`에 색상을 변경해야 해서 웹팩으로 svg를 컴포넌트화 하는 설정을 해서 원래 잘 나오던 이미지가 나오지 않는 거 같네요...
우선 그 부분은 png 파일로 변경하면 나올 거 같아요!
코드를 전반적으로 되게 깔끔하게 작성하시는 거 같아서 술술 읽혔네요👍

2024-05-28 14:43 UTC, devwqc commented on src/components/common/Badge/ProfileImgBadge.tsx
> +        src={profileImage.length > 0 ? profileImage : defaultProfileImg}
💊아마 여기서 `defaultProfileImg`가 안 뜨는 거 같은데
지금 `svg` 파일들을 웹펙으로 리액트 컴포넌트로 변환해서 발생하는 거 같아요
해당 이미지를 피그마에서 `svg`가 아니라 `png`로 다운로드해서 적용하면 될 거 같습니다!

2024-05-28 14:43 UTC, devwqc commented on src/utils/formatDate.ts
> +}
👍함수로 따로 만드신 거 좋네요!!
💊로직에 상관없긴 한데 인자로 `createdAt`를 받으니까 `createdAt`를 위한 함수인가? 생각이 들 수 있을 거 같아서 공통적인 `date`와 관련된 변수명으로 지으면 어떨까 싶어요

2024-05-28 14:43 UTC, devwqc commented on src/components/common/review/Textarea.tsx
> +    }
❓ `disabled`가 아닐 때는 크기를 동적으로 변하게 하지 않아도 되나요?!

2024-05-28 14:43 UTC, devwqc commented on src/components/common/review/ReviewBox.module.scss
> +  }
💊요기 `태그 선택자`에 클래스명 붙여서 사용하면 더 좋을 거 같아요

💬근데 여러 사이트 분석하다 보니까 이렇게 자식, 자손 관계로 `태그 선택자`를 사용하는 경우가 많더라구요?
그래서 이렇게 종속된 경우에는 `태그 선택자`를 사용해도 괜찮은 건지는 잘 모르겠어요...
그래도 보통은 `클래스 선택자`를 권장하니까 그렇게 따르는 게 좋을 거 같다는 생각입니다!

2024-05-29 01:50 UTC, Seoin02 commented on src/components/common/review/ReviewBox.module.scss
> +  }
태그 선택자로 스타일을 주면 이후 같은 태그를 사용할 때 의도하지 않은 스타일이 적용될 수 있기 때문에 클래스 선택자를 추천합니다

2024-05-29 01:59 UTC, Seoin02 approved these changes
👍🏻민영님 고생많으셨습니다! 천천히 하셔도 괜찮으니 너무 부담갖지 않으시길 바라요💗💗💗💗💗

2024-05-29 01:59 UTC, Seoin02 commented on src/assets/svgs/defaultProfileImg.svg
💊이건 저희 로고라서 logo라고 이름을 바꿔도 좋을 것 같아요! 로고 크기와 다른 기본 프로필 이미지 사이즈를 가진 친구라면 그냥 둬도 괜찮을 것 같습니다

2024-05-29 01:59 UTC, Seoin02 commented on src/components/common/review/ReviewBox.module.scss
> +  color: $color-black;
👍🏻컬러 변수 적용한 것 좋네용

2024-05-29 01:59 UTC, Seoin02 commented on src/utils/formatDate.ts
> +  const month = String(date.getMonth() + 1).padStart(2, '0');
❓pad가 뭘 뜻하는 걸까요?

2024-05-29 03:05 UTC, minyoung0503 commented on src/components/common/Badge/ProfileImgBadge.tsx
> +        src={profileImage.length > 0 ? profileImage : defaultProfileImg}
[9e66a99](https://github.com/Together-3team/petFrontend/pull/60/commits/9e66a99272697e8e30c753a9cbf66f15d06a90a5)

됐어요 !~!~!~!~!~!~ 감사합니당 🙇🏻‍♀️

2024-05-29 03:08 UTC, minyoung0503 commented on src/utils/formatDate.ts
> +}
[c91ecb1](https://github.com/Together-3team/petFrontend/pull/60/commits/c91ecb123d1068a96e7471c1579ef534ea3751a6)

timestamp로 변경해보았어요 !

2024-05-29 03:12 UTC, minyoung0503 commented on src/components/common/review/Textarea.tsx
> +    }
리뷰를 작성할 때 사용되는 textarea는 크기가 동적으로 변하게 되면 입력하는 값에 따라 리뷰 작성 화면에 있는 요소들이 같이 움직일 것 같아서 크기를 고정하고 scrollbar로 움직일 수 있게 했어요 !

2024-05-29 03:13 UTC, minyoung0503 commented on src/components/common/review/ReviewBox.module.scss
> +  }
[09ff59b](https://github.com/Together-3team/petFrontend/pull/60/commits/09ff59b0488710ec126db971f12d0f4f756ef2f9)

저도 그게 좀 거슬렸는데 봉찬님이랑 서인님한테 걸려버렸네요 ㅋ_ㅋ 수정했씁니다 !!

2024-05-29 03:15 UTC, minyoung0503 commented on src/assets/svgs/defaultProfileImg.svg
[9e66a99](https://github.com/Together-3team/petFrontend/pull/60/commits/9e66a99272697e8e30c753a9cbf66f15d06a90a5)

그럴까 생각했는데 svg 인식이 안 돼서 다른 크기의 png 형식으로 바꿔가지고 logo로 사용은 못 할 것 같아요 ㅠ_ㅠ

2024-05-29 03:19 UTC, minyoung0503 commented on src/utils/formatDate.ts
> +  const month = String(date.getMonth() + 1).padStart(2, '0');
gpt가 짜준 코드라서 gpt 한테 물어봤습니당 ㅎ_ㅎ

`padStart`메서드는 JavaScript의 문자열 메서드 중 하나로, 문자열의 시작을 지정된 길이에 맞추기 위해 다른 문자열로 채우는 역할을 합니다. 이 메서드는 ECMAScript 2017(ES8)에 추가되었습니다.

아마 날짜가 한 자릿수면 앞에 0을 추가해서 두 자리로 맞춰주는 메서드 같아요 !!
ex) 5월 -> 05 / 1일 -> 01

2024-05-29 06:32 UTC, Seoin02 commented on src/utils/formatDate.ts
> +  const month = String(date.getMonth() + 1).padStart(2, '0');
오홍 그렇군요!

2024-05-29 06:33 UTC, Seoin02 approved these changes

2024-05-29 06:59 UTC, devwqc approved these changes

2024-05-29 06:59 UTC, merged