[서인] signup 페이지 / UI 구현
Together-3team/petFrontend pull request #75
Opened 2024-05-31 12:19 UTC by Seoin02

## 🔥관련 이슈

- #69 

## :grin:주요 변경 사항

- signup 페이지 UI 구현
- Form 유효성 검사 로직 구현
- BackButton 공통 컴포넌트 구현

## 📄스크린샷
![signup UI](https://github.com/Together-3team/petFrontend/assets/144193370/48fe4653-b786-4048-841e-61781c578bd7)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- 닉네임 중복 유효성 검사 로직 구현해야 합니다.
- 전체 동의 input check 구현 못했습니다. 로직을 짜봤는데 동작하지 않아서 멘토님께 질문하려고요ㅠ
- custom input 공통 컴포넌트 구현해야 합니다.

## 💌리뷰 작성

칭찬: 👍 / 수정 요청: ❗ / 질문: ❓ / 제안: 💊 / 여담: 💬

2024-05-31 13:05 UTC, devwqc requested changes
서인님 감사합니다~👍💯🥇👍💯🥇👍💯🥇

signup 페이지 ui 되게 잘 뽑혔네요!
약관 동의 부분에 체크 박스는 css 작업이 아직 덜 된 부분 맞나요?
피그마에는 분홍색인데 미리보기에선 검은색이네요

전체적으로 잘 만드신 거 같아요~~👍
다만 `Yup` validation 처리하는 `filed`는 다른 곳에서도 쓰여서 재사용 가능하게 변경하면 더 좋을 거 같습니다!

어제오늘 집에 들어가지도 못하셨는데 얼른 퇴근하시고... 푹 쉬세요

2024-05-31 13:05 UTC, devwqc commented on src/components/common/BackButton/index.tsx
> +  return <LeftArrow width={24} height={24} onClick={href ? handleClick : handleBack} alt="뒤로 가기 버튼" />;
💊지금은 바로 `svg`를 컴포넌트로 사용했는데 보통 어떤 작업을 수행하는 건 `button`의 역할이니까 `button`으로 감싸면 더 시맨틱 할 거 같아요~

2024-05-31 13:05 UTC, devwqc commented on src/components/common/Input/index.tsx
> +      {label && <label className={cx(labelStyle)}>{label}</label>}
❓💊혹시 `htmlFor` 제거하신 이유가 있을까요? `htmlFor`가 있어야 `input`이랑 연동돼서 필요할 거 같다는 생각이 들어요

2024-05-31 13:05 UTC, devwqc commented on src/components/auth/SignupForm/index.tsx
> +          marketing={register('marketingAgreement')}
💊 지금 `_app.tsx`에 `FormProvider`를 등록하셨는데 `SignupForm`에 `FormProvier`를 등록하면 `UserAgreement`에 따로 `register`를 넘기지 않아도 `useFormContext`로 동기화 할 수 있을 거 같은데 서인님은 어떻게 생각하시나요?

2024-05-31 13:05 UTC, devwqc commented on src/pages/_app.tsx
> +        <FormProvider {...methods}>
💊이건 `SignupForm` 쪽에 코멘트 남겼습니다!

2024-05-31 13:05 UTC, devwqc commented on package.json
> +    "lint-staged": "^15.2.5",
❓ `lint-staged` 패치 버전을 높이신 이유가 있을까요?

2024-05-31 13:05 UTC, devwqc commented on src/components/auth/SignupForm/index.tsx
> +  marketingAgreement: Yup.boolean().required(),
💊 보니까 연락처, 이용약관 등 배송지, 주문에서 중복으로 사용되는 경우가 있더라구요
전에 멘토링 때 `validation` 재사용에 대해서 알려주셨는데 활용해 보면 좋을 거 같아요!!
따로 파일 만들어서 `export`하면 될 거 같네요?
![스크린샷 2024-05-28 211910](https://github.com/Together-3team/petFrontend/assets/98067115/a5bcaa05-d0a6-419c-8f16-639468cd4723)

2024-05-31 13:05 UTC, devwqc commented on src/components/common/BackButton/index.tsx
> +  }
💊 이거는 `handleClick` 하나로 처리할 수 있을 거 같아요~

밑에는 참고용입니다!
```suggestion
  function handleClick() {
    if (href) {
      router.push(href);
      return;
    }
    router.back();
  }
```

2024-05-31 13:05 UTC, devwqc commented on src/components/auth/SignupForm/UserAgreement.tsx
> +  }
❓이렇게 했을 때 동작 안 하나요?
`<input type="checkbox" onClick={handleSelectAll} /> 전체 동의`

2024-05-31 13:14 UTC, Seoin02 commented on package.json
> +    "lint-staged": "^15.2.5",
저번에 충돌 해결하다가 높인 것 같아요...ㅎ...

2024-06-01 12:21 UTC, Seoin02 commented on src/components/common/BackButton/index.tsx
> +  return <LeftArrow width={24} height={24} onClick={href ? handleClick : handleBack} alt="뒤로 가기 버튼" />;
반영했습니다. 시맨틱한 코드 중요하죠 감사합니다!

2024-06-01 12:25 UTC, Seoin02 commented on src/components/common/Input/index.tsx
> +      {label && <label className={cx(labelStyle)}>{label}</label>}
추가했습니다

2024-06-01 12:25 UTC, Seoin02 commented on src/components/auth/SignupForm/index.tsx
> +          marketing={register('marketingAgreement')}
덕분에 해결했습니다! 역시 봉찬님의 코드리뷰는 최고네요... 감사합니다!

2024-06-01 12:27 UTC, Seoin02 commented on src/components/auth/SignupForm/index.tsx
> +  marketingAgreement: Yup.boolean().required(),
반영했습니다! 감사합니다~~

2024-06-01 12:41 UTC, Seoin02 commented on src/components/common/BackButton/index.tsx
> +  }
반영했습니다 감사합니다!

2024-06-03 01:48 UTC, devwqc requested changes
서인님 감사합니다 👍👍👍👍💯💯💪

`Provider`가 많이 어렵죠? `CheckOnly`의 재사용에 대해서 고민 더 해보면 좋을 거 같습니다!

2024-06-03 01:48 UTC, devwqc commented on src/components/common/CheckOnly/index.tsx
> +  const { register } = useFormContext<FormValues>();
💊`CheckOnly`를 공통 컴포넌트로 사용하려면 `rest props`를 받아서 `input`에 넣어주는 방식으로 변경이 필요할 거 같아요!
지금처럼 안에서 `register`를 사용할 때 특히 제네릭으로 `FormValues`를 고정하면 이건 `SignupForm`에서만 사용이 가능하기 때문에 사용처에서 `register`를 넘겨주는 방식으로 하면 어떨까 싶어요👍

2024-06-03 01:56 UTC, minyoung0503 approved these changes
서인님 고생하셨어요 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️

2024-06-03 04:55 UTC, Seoin02 commented on src/components/common/CheckOnly/index.tsx
> +  const { register } = useFormContext<FormValues>();
아래처럼 수정했습니다.
```javascript
interface CheckOnlyProps {
  name?: 'nickname' | 'phoneNumber' | 'ageCheck' | 'serviceAgreement' | 'privatePolicy' | 'marketingAgreement';
}

export default function CheckOnly({
  name,
  type,
  className,
  ...rest
}: CheckOnlyProps & InputHTMLAttributes<HTMLInputElement>) {
  const { register } = useFormContext<FormValues>();
  return (
    <label className={styles.checkboxLabel}>
      <input
        type="checkbox"
        className={`${styles.checkboxInput} ${className}`}
        {...(name && register(name))}
        {...rest}
      />
      <div className={styles.checkIcon} />
    </label>
  );
}
```

2024-06-03 07:38 UTC, devwqc approved these changes

2024-06-03 10:08 UTC, merged